yolo task=detect\
     mode=train\
     model=yolo11n.pt\
     data=PDC/data.yaml\
     epochs=1024\
     imgsz=960,640\
     patience=0\
     rect=True\
     device=3\
     seed=42\
     box=100\
     plots=True