CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 \
yolo task=detect\
     mode=train\
     model=yolov10x.pt\
     data=PDCu/data.yaml\
     epochs=512\
     imgsz=1280\
     patience=128\
     mosaic=0.0\
     mixup=0.0\
     degrees=0\
     translate=0.0\
     shear=0.0\
     scale=0.5\
     iou=0.8\
     rect=True\
     device=2\
     seed=42\
     box=64\
     plots=True\
     project=runs